services:
  # Django backend service (internal only)
  backend:
    build:
      context: ..
      dockerfile: k8s/Dockerfile
    container_name: django-backend
    # No external ports - only accessible via nginx proxy
    expose:
      - "8000"
    volumes:
      # Mount the backend directory for development
      - ../backend:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=django_config.settings
      - SECRET_KEY=dev-secret-key-change-in-production
    restart: unless-stopped
    labels:
      - "project=simple-app"
      - "environment=development"
      - "service=backend"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - app-network

  # Nginx reverse proxy (unified frontend + API gateway)
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "3000:80"
    volumes:
      # Mount the frontend directory for static files
      - ../frontend:/usr/share/nginx/html
      # Mount custom nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    labels:
      - "project=simple-app"
      - "environment=development"
      - "service=proxy"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
