# Staging Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-staging
  namespace: staging
spec:
  replicas: 1  # Single replica for staging
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Allow the single pod to be terminated
      maxSurge: 1        # Allow one extra pod during rollout
  selector:
    matchLabels:
      app: simple-app-staging
  template:
    metadata:
      labels:
        app: simple-app-staging
    spec:
      containers:
        # Nginx Frontend Container (serves frontend + proxy to Django)
        - name: nginx-frontend
          image: wilsonw321/simple-app-nginx:staging-74cef7a580ade1b6e03197425dfc063cc36e4fe6
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
        
        # Django Backend Container (API server)
        - name: django-backend
          image: wilsonw321/simple-app-django:staging-74cef7a580ade1b6e03197425dfc063cc36e4fe6
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: ENVIRONMENT
              value: "staging"
            - name: DEBUG
              value: "True"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret-staging
                  key: secret-key
            - name: ALLOWED_HOSTS
              value: "localhost,127.0.0.1,backend,django-backend,staging.yourdomain.com,*"
          livenessProbe:
            httpGet:
              path: /api/test/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/test/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10

---
# Staging Service
apiVersion: v1
kind: Service
metadata:
  name: simple-app-staging-service
  namespace: staging
spec:
  selector:
    app: simple-app-staging
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP

---
# Staging Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-staging-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: staging.yourdomain.com  # Different host for staging
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-app-staging-service
                port:
                  number: 3001 